### ISSUE TITLE
Wrong dihedral in Entry CILE and NILE in aminoacids.rtp in amber99sb-star-ildn-q.ff

### ISSUE THREAD

**Issue by Laura-Schulz** [bestlab/force_fields#3]
Hello, 
I assume a typing error has slipped in the aminoacids.rtp file in the amber99sb-star-ildn-q forcefield. 
The dihedral "     B    CA    CB   CG2        torsion_ILE_N_CA_CB_CG2_mult2" in the entries CILE and NILE should be "     N    CA    CB   CG2        torsion_ILE_N_CA_CB_CG2_mult2" or am I missing something?

**Comment by bestrob** [comment]
Thanks -sorry for the delayed response. This indeed seems to be a typo, fixed now!
